from typing import Callable

import streamlit

from src.app.templates.common import load_style


def button_decorator(func: Callable):
    """
    A decorator that applies a Streamlit style to a function that generates a button.

    :param func: The function to be decorated.
    :type func: callable

    :return: A new function that applies a Streamlit style to the button generated by `func`.
    :rtype: callable
    """

    def wrapper(*args, **kwargs):
        streamlit.write(load_style(), unsafe_allow_html=True)
        return func(*args, **kwargs)

    return wrapper
